/**
 * GENERATED FILE — DO NOT EDIT
 *
 * Auto-generated from artifacts/openapi.json by openapi-typescript.
 * Source: @asc/contract route definitions.
 *
 * Regenerate: npm run generate:all
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cases with optional filters */
        get: operations["cases.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single case by ID */
        get: operations["cases.get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update case fields */
        patch: operations["cases.update"];
        trace?: never;
    };
    "/cases/{caseId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a requested case */
        post: operations["cases.approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a requested case */
        post: operations["cases.reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{caseId}/assign-room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign or unassign a room for a case */
        patch: operations["cases.assignRoom"];
        trace?: never;
    };
    "/inventory/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a single inventory event */
        post: operations["inventory.createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/events/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record multiple inventory events in one request */
        post: operations["inventory.bulkEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all catalog items */
        get: operations["catalog.list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{catalogId}/identifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a barcode/identifier to a catalog item */
        post: operations["catalog.addIdentifier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{catalogId}/identifiers/{identifierId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a catalog identifier */
        delete: operations["catalog.deleteIdentifier"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/{catalogId}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a catalog image */
        delete: operations["catalog.deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "cases.list": {
        parameters: {
            query?: {
                date?: string;
                status?: string;
                active?: string;
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            cases: {
                                /** Format: uuid */
                                id: string;
                                caseNumber: string;
                                /** Format: uuid */
                                facilityId: string;
                                scheduledDate: string | null;
                                scheduledTime: string | null;
                                requestedDate: string | null;
                                requestedTime: string | null;
                                /** Format: uuid */
                                surgeonId: string;
                                surgeonName: string;
                                procedureName: string;
                                preferenceCardVersionId: string | null;
                                /** @enum {string} */
                                status: "DRAFT" | "REQUESTED" | "SCHEDULED" | "READY" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "REJECTED";
                                notes: string | null;
                                isActive: boolean;
                                activatedAt: string | null;
                                activatedByUserId: string | null;
                                isCancelled: boolean;
                                cancelledAt: string | null;
                                cancelledByUserId: string | null;
                                rejectedAt: string | null;
                                rejectedByUserId: string | null;
                                rejectionReason: string | null;
                                createdAt: string;
                                updatedAt: string;
                                roomId: string | null;
                                roomName: string | null;
                                estimatedDurationMinutes: number | null;
                                sortOrder: number | null;
                            }[];
                        };
                    };
                };
            };
        };
    };
    "cases.get": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            case: {
                                /** Format: uuid */
                                id: string;
                                caseNumber: string;
                                /** Format: uuid */
                                facilityId: string;
                                scheduledDate: string | null;
                                scheduledTime: string | null;
                                requestedDate: string | null;
                                requestedTime: string | null;
                                /** Format: uuid */
                                surgeonId: string;
                                surgeonName: string;
                                procedureName: string;
                                preferenceCardVersionId: string | null;
                                /** @enum {string} */
                                status: "DRAFT" | "REQUESTED" | "SCHEDULED" | "READY" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "REJECTED";
                                notes: string | null;
                                isActive: boolean;
                                activatedAt: string | null;
                                activatedByUserId: string | null;
                                isCancelled: boolean;
                                cancelledAt: string | null;
                                cancelledByUserId: string | null;
                                rejectedAt: string | null;
                                rejectedByUserId: string | null;
                                rejectionReason: string | null;
                                createdAt: string;
                                updatedAt: string;
                                roomId: string | null;
                                roomName: string | null;
                                estimatedDurationMinutes: number | null;
                                sortOrder: number | null;
                            };
                        };
                    };
                };
            };
        };
    };
    "cases.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    scheduledDate?: string;
                    scheduledTime?: string | null;
                    /** Format: uuid */
                    surgeonId?: string;
                    procedureName?: string;
                    /** Format: uuid */
                    preferenceCardVersionId?: string | null;
                    /** @enum {string} */
                    status?: "DRAFT" | "REQUESTED" | "SCHEDULED" | "READY" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "REJECTED";
                    notes?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            case: {
                                /** Format: uuid */
                                id: string;
                                caseNumber: string;
                                /** Format: uuid */
                                facilityId: string;
                                scheduledDate: string | null;
                                scheduledTime: string | null;
                                requestedDate: string | null;
                                requestedTime: string | null;
                                /** Format: uuid */
                                surgeonId: string;
                                surgeonName: string;
                                procedureName: string;
                                preferenceCardVersionId: string | null;
                                /** @enum {string} */
                                status: "DRAFT" | "REQUESTED" | "SCHEDULED" | "READY" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "REJECTED";
                                notes: string | null;
                                isActive: boolean;
                                activatedAt: string | null;
                                activatedByUserId: string | null;
                                isCancelled: boolean;
                                cancelledAt: string | null;
                                cancelledByUserId: string | null;
                                rejectedAt: string | null;
                                rejectedByUserId: string | null;
                                rejectionReason: string | null;
                                createdAt: string;
                                updatedAt: string;
                                roomId: string | null;
                                roomName: string | null;
                                estimatedDurationMinutes: number | null;
                                sortOrder: number | null;
                            };
                        };
                    };
                };
            };
        };
    };
    "cases.approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    scheduledDate: string;
                    scheduledTime?: string;
                    /** Format: uuid */
                    roomId?: string | null;
                    estimatedDurationMinutes?: number;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            case: {
                                /** Format: uuid */
                                id: string;
                                caseNumber: string;
                                /** Format: uuid */
                                facilityId: string;
                                scheduledDate: string | null;
                                scheduledTime: string | null;
                                requestedDate: string | null;
                                requestedTime: string | null;
                                /** Format: uuid */
                                surgeonId: string;
                                surgeonName: string;
                                procedureName: string;
                                preferenceCardVersionId: string | null;
                                /** @enum {string} */
                                status: "DRAFT" | "REQUESTED" | "SCHEDULED" | "READY" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "REJECTED";
                                notes: string | null;
                                isActive: boolean;
                                activatedAt: string | null;
                                activatedByUserId: string | null;
                                isCancelled: boolean;
                                cancelledAt: string | null;
                                cancelledByUserId: string | null;
                                rejectedAt: string | null;
                                rejectedByUserId: string | null;
                                rejectionReason: string | null;
                                createdAt: string;
                                updatedAt: string;
                                roomId: string | null;
                                roomName: string | null;
                                estimatedDurationMinutes: number | null;
                                sortOrder: number | null;
                            };
                        };
                    };
                };
            };
        };
    };
    "cases.reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            case: {
                                /** Format: uuid */
                                id: string;
                                caseNumber: string;
                                /** Format: uuid */
                                facilityId: string;
                                scheduledDate: string | null;
                                scheduledTime: string | null;
                                requestedDate: string | null;
                                requestedTime: string | null;
                                /** Format: uuid */
                                surgeonId: string;
                                surgeonName: string;
                                procedureName: string;
                                preferenceCardVersionId: string | null;
                                /** @enum {string} */
                                status: "DRAFT" | "REQUESTED" | "SCHEDULED" | "READY" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "REJECTED";
                                notes: string | null;
                                isActive: boolean;
                                activatedAt: string | null;
                                activatedByUserId: string | null;
                                isCancelled: boolean;
                                cancelledAt: string | null;
                                cancelledByUserId: string | null;
                                rejectedAt: string | null;
                                rejectedByUserId: string | null;
                                rejectionReason: string | null;
                                createdAt: string;
                                updatedAt: string;
                                roomId: string | null;
                                roomName: string | null;
                                estimatedDurationMinutes: number | null;
                                sortOrder: number | null;
                            };
                        };
                    };
                };
            };
        };
    };
    "cases.assignRoom": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    roomId: string | null;
                    sortOrder?: number;
                    estimatedDurationMinutes?: number;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            case: {
                                /** Format: uuid */
                                id: string;
                                caseNumber: string;
                                /** Format: uuid */
                                facilityId: string;
                                scheduledDate: string | null;
                                scheduledTime: string | null;
                                requestedDate: string | null;
                                requestedTime: string | null;
                                /** Format: uuid */
                                surgeonId: string;
                                surgeonName: string;
                                procedureName: string;
                                preferenceCardVersionId: string | null;
                                /** @enum {string} */
                                status: "DRAFT" | "REQUESTED" | "SCHEDULED" | "READY" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "REJECTED";
                                notes: string | null;
                                isActive: boolean;
                                activatedAt: string | null;
                                activatedByUserId: string | null;
                                isCancelled: boolean;
                                cancelledAt: string | null;
                                cancelledByUserId: string | null;
                                rejectedAt: string | null;
                                rejectedByUserId: string | null;
                                rejectionReason: string | null;
                                createdAt: string;
                                updatedAt: string;
                                roomId: string | null;
                                roomName: string | null;
                                estimatedDurationMinutes: number | null;
                                sortOrder: number | null;
                            };
                        };
                    };
                };
            };
        };
    };
    "inventory.createEvent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    inventoryItemId: string;
                    /** @enum {string} */
                    eventType: "RECEIVED" | "VERIFIED" | "LOCATION_CHANGED" | "RESERVED" | "RELEASED" | "CONSUMED" | "EXPIRED" | "RETURNED" | "ADJUSTED";
                    /** Format: uuid */
                    caseId?: string;
                    /** Format: uuid */
                    locationId?: string;
                    /** @enum {string} */
                    sterilityStatus?: "STERILE" | "NON_STERILE" | "EXPIRED" | "UNKNOWN";
                    notes?: string;
                    /** Format: uuid */
                    deviceEventId?: string;
                    /** Format: date-time */
                    occurredAt?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            success: boolean;
                        };
                    };
                };
            };
        };
    };
    "inventory.bulkEvents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    events: {
                        /** Format: uuid */
                        inventoryItemId: string;
                        /** @enum {string} */
                        eventType: "RECEIVED" | "VERIFIED" | "LOCATION_CHANGED" | "RESERVED" | "RELEASED" | "CONSUMED" | "EXPIRED" | "RETURNED" | "ADJUSTED";
                        /** Format: uuid */
                        caseId?: string;
                        /** Format: uuid */
                        locationId?: string;
                        /** @enum {string} */
                        sterilityStatus?: "STERILE" | "NON_STERILE" | "EXPIRED" | "UNKNOWN";
                        notes?: string;
                        /** Format: uuid */
                        deviceEventId?: string;
                        /** Format: date-time */
                        occurredAt?: string;
                    }[];
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            success: boolean;
                        };
                    };
                };
            };
        };
    };
    "catalog.list": {
        parameters: {
            query?: {
                category?: string;
                includeInactive?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                description: string | null;
                                /** @enum {string} */
                                category: "IMPLANT" | "INSTRUMENT" | "EQUIPMENT" | "MEDICATION" | "CONSUMABLE" | "PPE";
                                manufacturer: string | null;
                                catalogNumber: string | null;
                                requiresSterility: boolean;
                                isLoaner: boolean;
                                active: boolean;
                                requiresLotTracking: boolean;
                                requiresSerialTracking: boolean;
                                requiresExpirationTracking: boolean;
                                /** @enum {string} */
                                criticality: "CRITICAL" | "IMPORTANT" | "ROUTINE";
                                readinessRequired: boolean;
                                expirationWarningDays: number | null;
                                substitutable: boolean;
                                inventoryCount: number;
                                imageCount: number;
                                identifierCount: number;
                                createdAt: string;
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
    };
    "catalog.addIdentifier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    rawValue: string;
                    source?: string;
                };
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            identifier: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                catalogId: string;
                                identifierType: string;
                                rawValue: string;
                                source: string;
                                classification: string;
                                createdAt: string;
                                createdByUserId: string | null;
                                creatorName?: string | null;
                            };
                            gs1Data: {
                                gtin: string | null;
                                lot: string | null;
                                expiration: string | null;
                                serial: string | null;
                            } | null;
                        };
                    };
                };
            };
        };
    };
    "catalog.deleteIdentifier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogId: string;
                identifierId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "catalog.deleteImage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                catalogId: string;
                imageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
